name: traly
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.3.0
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.7
  go_router: ^15.1.2
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  flutter_svg_opt: 
  flutter_gen_runner: ^4.0.0


# The following section is specific to Flutter packages.
flutter_gen:
  assets:
    exclude:
    - flags/**
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
    image: true

flutter:

  uses-material-design: true


  #         weight: 700
  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/
    - assets/json/

  fonts:
    - family: Abnes
      fonts:
        - asset: assets/fonts/abnes/AbnesRegular.otf
          weight: 400

    - family: Proto Mono
      fonts:
        - asset: assets/fonts/proto_mono/ProtoMono-Medium.ttf
          weight: 400
    - family: Nico Moji
      fonts:
        - asset: assets/fonts/nico_moji/NicoMojiRegular.ttf
          weight: 400